name: Keepalive

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  keepalive:
    name: Keepalive
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          ref: keepalive
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name ${GITHUB_ACTOR}
          git config user.email ${GITHUB_ACTOR}@users.noreply.github.com
      - name: Update keepalive branch
        run: |
          git commit --amend --no-edit
          git push -f
